Repository apache/incubator-nemo, pull requests merged in 2018-06, with the labels that each got.

#55 [NEMO-127] Modify DefaultInterTaskDataStorePass not to overwrite property
  compiler/optimizer/src/main/java/edu/snu/nemo/compiler/optimizer/pass/compiletime/annotating/DefaultInterTaskDataStorePass.java
Labels: enhancement

#54 [NEMO-126] Split ScheduleGroup by pull StageEdges by PhysicalPlanGenerator
  compiler/optimizer/src/main/java/edu/snu/nemo/compiler/optimizer/pass/compiletime/annotating/DefaultScheduleGroupPass.java
  runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/PhysicalPlanGenerator.java
  runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/Stage.java
  runtime/common/src/main/java/edu/snu/nemo/runtime/common/plan/StageEdge.java
  runtime/master/src/test/java/edu/snu/nemo/runtime/master/scheduler/FaultToleranceTest.java
  tests/src/test/java/edu/snu/nemo/runtime/common/plan/PhysicalPlanGeneratorTest.java
  tests/src/test/java/edu/snu/nemo/tests/compiler/CompilerTestUtil.java
  tests/src/test/java/edu/snu/nemo/tests/compiler/optimizer/pass/compiletime/annotating/DefaultEdgeCoderPassTest.java
  tests/src/test/java/edu/snu/nemo/tests/compiler/optimizer/pass/compiletime/composite/DataSkewCompositePassTest.java
Labels: enhancement

#56 [NEMO-16] Implement collection of data from executor to client
  client/src/main/java/edu/snu/nemo/client/JobLauncher.java
  common/src/main/java/edu/snu/nemo/common/ContextImpl.java
  common/src/main/java/edu/snu/nemo/common/ir/vertex/transform/Transform.java
  common/src/test/java/edu/snu/nemo/common/ContextImplTest.java
  compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/core/SparkFrontendUtils.java
  compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/transform/CollectTransform.java
  compiler/frontend/spark/src/main/java/edu/snu/nemo/compiler/frontend/spark/transform/ReduceTransform.java
  examples/spark/src/test/java/edu/snu/nemo/examples/spark/MRJava.java
  examples/spark/src/test/java/edu/snu/nemo/examples/spark/SparkJava.java
  examples/spark/src/test/java/edu/snu/nemo/examples/spark/SparkScala.java
  runtime/common/src/main/java/edu/snu/nemo/runtime/common/message/ncs/NcsMessageEnvironment.java
  runtime/common/src/main/proto/ControlMessage.proto
  runtime/driver/src/main/java/edu/snu/nemo/driver/NemoDriver.java
  runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/Executor.java
  runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/task/TaskExecutor.java
  runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/datatransfer/DataTransferTest.java
  runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/task/TaskExecutorTest.java
  runtime/master/src/main/java/edu/snu/nemo/runtime/master/ClientRPC.java
  runtime/master/src/main/java/edu/snu/nemo/runtime/master/RuntimeMaster.java
  tests/src/test/java/edu/snu/nemo/client/ClientDriverRPCTest.java
Labels: bug, enhancement

#60 [NEMO-61] Fix lost execution metric collection problem
  runtime/common/src/main/java/edu/snu/nemo/runtime/common/message/ncs/NcsMessageEnvironment.java
  runtime/common/src/main/proto/ControlMessage.proto
  runtime/common/src/test/java/edu/snu/nemo/runtime/common/message/local/LocalMessageTest.java
  runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/Executor.java
  runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/MetricManagerWorker.java
  runtime/executor/src/main/java/edu/snu/nemo/runtime/executor/MetricMessageSender.java
  runtime/executor/src/test/java/edu/snu/nemo/runtime/executor/datatransfer/DataTransferTest.java
  runtime/master/src/main/java/edu/snu/nemo/runtime/master/MetricManagerMaster.java
  runtime/master/src/main/java/edu/snu/nemo/runtime/master/RuntimeMaster.java
  runtime/master/src/main/java/edu/snu/nemo/runtime/master/scheduler/ExecutorRegistry.java
  tests/src/test/java/edu/snu/nemo/runtime/master/MetricFlushTest.java
Labels: bug
